### ISSUE TITLE
Http control Ufo

### ISSUE THREAD

**Issue by Dylantje** [sidoh/ledenet_api#3]
Dear is see you have hacked the ufo rgbw controller..
Great job!!!!

I wil try to use this controller for my Home automation, Domoticz.
Is there perhaps a option that i can use your way with Http commands?
Domoticz can use the Http commands directly...
Or perhaps a script, domoticz can work with different types.

I did install the ledenet api, only now i am stuc.
Did install it on my RPi. 

How can i use the api on a simple way.
I do not understand where i can place/put the api [ in putty is get strange values ]
Perhaps you have some examples, of your nice work

I am not ict expert... :-(
Hope you will help me with your nice hack...
I do not have a Ufo j@ this moment [ orderd 2  ] only i will learn before i got 1...

Thanks!!

**Comment by sidoh** [comment]
You could use [ha_gateway](https://github.com/sidoh/ha_gateway). Allows you to set up a RESTful API and has an integration with ledenet_api.

**Comment by Dylantje** [comment]
mm Thanks Ha is on the RPi..
Like i say... no ict expert :-)

I read that need the HW adres [ i do not have yet ] this is the mac?
what is the name for? so i now what controller? or the name in my lan? 
Can i ad more controller in the config file?

Only i do not understand how i give a command...

**Comment by sidoh** [comment]
Yeah, hardware address is MAC address. Are you looking at the example config file?

``` yaml
      # There are a couple of ways you can specify which device you'd like
      # to control:
      #   1. Specify no params. Control an arbitrary (maybe the only?) LEDENET
      #      device on your network.
      #   2. Specify a hardware address. ha_gateway will attempt to resolve
      #      the host from the hw addr using a discovery protocol. This is
      #      preferable if you don't have a hostname or static IP for the
      #      LEDENET device.
      #   3. Specify a host directly.
      hw_addr: 00:00:00:00:00:00
      host: ledenet1
```

You can also use `host` if you want to hardcode a local IP address or hostname. `hw_addr` is just more robust to network changes.
